version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.3

workflows:
  tests:
    jobs:
      - cypress/run:
          package-manager: yarn
          cypress-command: yarn test
          name: Run Cypress tests
          post-steps:
            - store_artifacts:
                path: cypress/reports
